# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "../", "/workshop-docker", mount_options: ["dmode=775,fmode=664"]
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define :dockerbox, primary: true do |dockerbox|
    dockerbox.vm.network :forwarded_port, host: 8000, guest: 80
    dockerbox.vm.network "private_network", ip: "192.168.50.50"
    dockerbox.vm.provision "shell", path: "provision-bootstrap.sh"
    dockerbox.vm.hostname = "dockerbox"
  end
end
